clear all;
close all;
t=[0:0.0001:2];
fm=5;
m = cos(2*pi*fm*t);
subplot(5,1,1);
plot(t,m);
title('message signal');
xlabel('Time');
ylabel('Amplitude');
grid on;
fc=50;
c=cos(2*pi*fc*t);
subplot(5,1,2);
plot(t,c);
title('carrier signal');
xlabel('Time');
ylabel('Amplitude');
grid on;
m1=0.5;
s1=(1+(m1*m)).*c;
subplot(5,1,3);
plot(t,s1);
title('under modulation signal');
xlabel('Time');
ylabel('Amplitude');
grid on;
m2=1;
s2=(1+(m2*m)).*c;
subplot(5,1,4);
plot(t,s2);
title('critical signal');
xlabel('Time');
ylabel('Amplitude');
grid on;
m3=1,5;
s3=(1+(m3*m)).*c;
subplot(5,1,5);
plot(t,s3);
title('over modulation signal');
xlabel('Time');
ylabel('Amplitude');
grid on;
%axis([0,2,-2.5,2.5]);


