clc;
clear all;
close all;
fm=10;
B=10;
t=0:0.0001:0.50;
m=sin(2*pi*fm*t);
subplot(3,1,1);
plot(t,m);
xlabel('Time');
ylabel('Amplitude');
title('Message signal');
grid on;
fc=100;
c=sin(2*pi*fc*t);
subplot(3,1,2);
plot(t,c);
xlabel('Time');
ylabel('Amplitude');
title('carrier signal');
grid on;

y=sin(2*pi*fc*t+(B.*sin(2*pi*fm*t)));
subplot(3,1,3);
plot(t,y);
xlabel('Time');
ylabel('Amplitude');
title('phase Modulated  signal');
grid on;
