close all;
w = [0:1:500]*pi/500;
H = exp(j*w)./(exp(j*w)-0.9*ones(1,501));
magH = abs(H);
angH = angle(H);
subplot(2,1,1);
plot(w/pi,magH);
grid on;
title('Magnitude resposnse');
xlabel('frequency in pi unit');
ylabel('Magnitude/H');
subplot(2,1,2);
plot(w/pi,angH/pi);
grid on;
title('phase response');
xlabel('frequency in pi units');
ylabel('phase in pi radians');
